name: Bug Report
description: Create a report to help us improve
title: "[Bug]:"
labels: [ "bug" ]
assignees:
  - dearxuecom
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: |-
        Make SURE that you follow these statements.
      options:
        - label: I have updated the ApiHug plugin to the **latest version**
          required: true

        - label: I have updated the ApiHug SDK to the **latest version**
          required: true

        - label: I followed the [handbook](https://github.com/apihug/apihug.com/tree/master/docs/handbook) and the [features](https://github.com/apihug/apihug.com/tree/master/docs/IDE) introduction and I double checked my configuration.
          required: true

        - label: I have check [FAQ](https://github.com/apihug/apihug.com/blob/master/docs/IDE/999_FAQ.md) and I did not find the answer.
          required: true

        - label: I have searched closed issue and I did not find the answer.
          required: true
  - type: checkboxes
    id: operating-systems
    attributes:
      label: Which operating system are you using?
      options:
        - label: macOS
        - label: Windows
        - label: Linux

  - type: input
    id: ideaVersion
    attributes:
      label: IDEA version
      value:
    validations:
      required: true
  - type: input
    id: pluginVersion
    attributes:
      label: Plugin version
      value:
      placeholder: version of ApiHug - API design Copilot
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Describe the bug

        > If applicable, add screenshots or record screen to help explain your problem.                
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error log
      description: Please copy and paste the error log of plugin. This will help us better to find and solve problems

  - type: markdown
    attributes:
      value: |
        Check [homepage](https://github.com/apihug/apihug.com/) for QR code to join the chat group.